# Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    tier: backend
    project: roboshop
    component: shipping

data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
# Deployment set
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  annotations:
    kubernetes.io/change-cause: "deploying shipping:1.2.0"
  labels:
    tier: backend
    project: roboshop
    component: shipping

spec:
  replicas: 1
  selector:
    # This match labels will go and find the pods who contain these labels
    matchLabels:
      tier: backend
      project: roboshop
      component: shipping

  # This is a POD definition/template (pod is a subset of replica-set)
  template:
    metadata:
      # POD Labels, these labels will refer in replica-set selector
      labels:
        tier: backend
        project: roboshop
        component: shipping
    spec:
      containers:
        - name: shipping
          image: maheshbabu22neeli/shipping:1.2.0
          imagePullPolicy: Always   # Always pull the image from ECR/GitHub

          resources:
            # this is minimum resource, soft limit
            requests:
              memory: "128Mi"  # RAM
              cpu: "200m"

            # this is maximum resource, hard limit
            limits:
              memory: "256Mi"  # RAM
              cpu: "250m"

          readinessProbe:
            tcpSocket:
              port: 8080
            #httpGet:
              #path: /health
              #port: 8080
            initialDelaySeconds: 20
            failureThreshold: 2
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          # This container will refer to the above created config map with name 'shipping'
          envFrom:
          - configMapRef:
              name: shipping

---
# Adding service for shipping
# We are taking ClusterIP service as this communicate with internal POD's only
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    tier: backend
    project: roboshop
    component: shipping

spec:
  selector:
    # selecting shipping pod based on the below labels and add to the service
    tier: backend
    project: roboshop
    component: shipping
  ports:
    - protocol: TCP
      port: 8080          # service port
      targetPort: 8080    # container port
